"use client";
import Link from 'next/link'; import { demoReports, specialists } from '@/lib/demo';
export function DemoPage({ kind }: { kind: 'upload'|'archive'|'reports'|'specialists'|'summary' }) {
 if (kind==='upload') return <section><h1>Upload a medical report</h1><p className="lead">PDF, JPG, or PNG</p><div className="drop">Drop a report here or <button className="link">choose a file</button><small>Demo preview — upload and extraction are simulated.</small></div><select><option>Mammogram Report</option><option>Breast Ultrasound Report</option><option>Breast MRI Report</option><option>Pathology/Biopsy Report</option></select><table><tbody>{[['Report date','02 Sep 2026'],['Imaging type','Breast ultrasound'],['BI-RADS category','Demo preview'],['Breast side','Right'],['Finding summary','Demo preview'],['Follow-up recommendation','Clinical follow-up may be appropriate']].map(x=><tr key={x[0]}><th>{x[0]}</th><td>{x[1]}</td></tr>)}</tbody></table><button className="btn">Save to Reports</button></section>;
 if(kind==='archive') return <section><h1>Scan archive</h1><p className="lead">Secure record organization. Images are not interpreted by Diagnex.</p><div className="cards">{['Mammogram','Breast Ultrasound','Breast MRI'].map(x=><article className="card" key={x}><h3>{x}</h3><p>DICOM verified · Stored securely · Radiology report attached</p><button className="secondary">View Associated Report</button><small>Research feature. Not used for patient diagnosis.</small></article>)}</div></section>;
 if(kind==='reports') return <section><h1>Saved reports</h1><p className="lead">Your organized breast-health records</p><div className="cards">{demoReports.map(r=><article className="card" key={r.id}><h3>{r.title}</h3><p>{r.date} · {r.category}</p><span className="pill">{r.status}</span><p><button className="secondary">View Report</button> <button className="secondary">Download Report</button> <button className="link">Delete</button></p></article>)}</div></section>;
 if(kind==='specialists') return <section><h1>Find a specialist</h1><p className="lead">Demo contact directory</p><div className="filters"><input placeholder="City"/><select><option>All specialties</option><option>Breast Surgeon</option><option>Gynecologist</option><option>Oncologist</option><option>Radiologist</option><option>Genetic Counselor</option></select></div><div className="cards">{specialists.map(s=><article className="card" key={s[0]}><h3>{s[0]}</h3><p>{s[1]} · {s[2]}</p><p>{s[3]} · demo@diagnex.example<br/>{s[4]} · Mon–Fri, 9am–5pm</p><a className="secondary" target="_blank" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(s[2]+' '+s[4])}>Open in Maps</a></article>)}</div><p className="notice">Diagnex provides contact information only. Confirm availability, qualifications, fees, and treatment options directly with the provider.</p></section>;
 return <section><h1>Breast awareness summary</h1><article className="summary"><p><b>Reported concern:</b> New lump with pain</p><p><b>Reported location:</b> Right breast, upper area</p><p><b>Duration:</b> A few days</p><p><b>Associated changes:</b> Pain</p><p><b>Suggested urgency:</b> Prompt clinical assessment recommended</p><p><b>Recommended next step:</b> Arrange a clinical appointment.</p></article><p className="notice">This summary is based on information entered by the user. It is not a diagnosis. A qualified clinician should assess new or persistent breast changes.</p><Link className="btn" href="/dashboard/reports">Save Summary</Link> <Link className="secondary" href="/dashboard/upload">Upload Existing Report</Link> <Link className="secondary" href="/dashboard/specialists">Find a Specialist</Link></section>;
}
