"""
Diagnex Backend — ORM Models

All database models for the application. The AuditLog table is
append-only — application code must never UPDATE or DELETE audit rows.
"""

import enum
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from app.db.base import Base


# ── Enums ────────────────────────────────────────────────────

class UserRole(str, enum.Enum):
    PATIENT = "patient"
    DOCTOR = "doctor"
    ADMIN = "admin"
    RESEARCHER = "researcher"


class ScreeningType(str, enum.Enum):
    DIABETES = "diabetes"
    BREAST_CANCER = "breast_cancer"


class RiskCategory(str, enum.Enum):
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    VERY_HIGH = "very_high"


# ── Helper ───────────────────────────────────────────────────

def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ── Users ────────────────────────────────────────────────────

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String(255), unique=True, nullable=False, index=True)
    hashed_password = Column(String(255), nullable=False)
    full_name = Column(String(255), nullable=False)
    role = Column(Enum(UserRole), nullable=False, default=UserRole.PATIENT)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False)
    updated_at = Column(DateTime(timezone=True), default=_utcnow, onupdate=_utcnow)

    # Relationships
    patient_profile = relationship("PatientProfile", back_populates="user", uselist=False)
    screening_sessions = relationship("ScreeningSession", back_populates="patient")
    file_uploads = relationship("FileUpload", back_populates="patient")
    reviews = relationship("ScreeningResult", foreign_keys="ScreeningResult.reviewed_by")


class PatientProfile(Base):
    __tablename__ = "patient_profiles"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), unique=True, nullable=False)
    date_of_birth = Column(String(255), nullable=True)  # Encrypted
    gender = Column(String(50), nullable=True)
    phone_encrypted = Column(String(512), nullable=True)  # Encrypted
    address_encrypted = Column(Text, nullable=True)  # Encrypted
    medical_history_encrypted = Column(Text, nullable=True)  # Encrypted
    emergency_contact_encrypted = Column(Text, nullable=True)  # Encrypted
    created_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False)

    # Relationships
    user = relationship("User", back_populates="patient_profile")


# ── Screening ────────────────────────────────────────────────

class ScreeningSession(Base):
    __tablename__ = "screening_sessions"

    id = Column(Integer, primary_key=True, index=True)
    patient_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    screening_type = Column(Enum(ScreeningType), nullable=False)
    input_data_encrypted = Column(Text, nullable=False)  # Encrypted JSON of form inputs
    created_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False)

    # Relationships
    patient = relationship("User", back_populates="screening_sessions")
    result = relationship("ScreeningResult", back_populates="session", uselist=False)


class ScreeningResult(Base):
    __tablename__ = "screening_results"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("screening_sessions.id"), unique=True, nullable=False)
    model_name = Column(String(100), nullable=False)
    model_version = Column(String(50), nullable=False)
    dataset_version = Column(String(50), nullable=False)
    risk_score = Column(Float, nullable=False)
    risk_category = Column(Enum(RiskCategory), nullable=False)
    explanation = Column(Text, nullable=True)  # Feature importance JSON
    ai_disclaimer = Column(
        Text,
        nullable=False,
        default=(
            "SCREENING ESTIMATE ONLY — This is NOT a medical diagnosis. "
            "This result was generated by a research-only AI model and requires "
            "clinician review before any clinical decisions are made."
        ),
    )
    clinician_reviewed = Column(Boolean, default=False, nullable=False)
    reviewed_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    clinical_notes = Column(Text, nullable=True)
    reviewed_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False)

    # Relationships
    session = relationship("ScreeningSession", back_populates="result")
    reviewer = relationship("User", foreign_keys=[reviewed_by], overlaps="reviews")


# ── File Uploads ─────────────────────────────────────────────

class FileUpload(Base):
    __tablename__ = "file_uploads"

    id = Column(Integer, primary_key=True, index=True)
    patient_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    original_filename_encrypted = Column(String(512), nullable=False)  # Encrypted
    stored_filename = Column(String(255), nullable=False)  # UUID-based, no PHI
    file_type = Column(String(100), nullable=False)
    file_size_bytes = Column(Integer, nullable=False)
    file_hash = Column(String(64), nullable=False)  # SHA-256 of encrypted content
    description = Column(Text, nullable=True)
    uploaded_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False)

    # Relationships
    patient = relationship("User", back_populates="file_uploads")


# ── Audit Log (Append-Only) ─────────────────────────────────

class AuditLog(Base):
    """
    Immutable audit trail. Application code must NEVER issue
    UPDATE or DELETE statements against this table.
    """
    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, nullable=True)  # Nullable for system events
    role = Column(String(50), nullable=False, default="system")
    action = Column(String(100), nullable=False, index=True)
    resource = Column(String(100), nullable=False)
    resource_id = Column(String(100), nullable=True)
    ip_address = Column(String(45), nullable=True)
    details_hash = Column(String(64), nullable=True)  # SHA-256, never raw PHI
    timestamp = Column(DateTime(timezone=True), default=_utcnow, nullable=False, index=True)


# ── Model Registry ───────────────────────────────────────────

class ModelRegistry(Base):
    __tablename__ = "model_registry"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False, index=True)
    version = Column(String(50), nullable=False)
    dataset_version = Column(String(100), nullable=False)
    description = Column(Text, nullable=True)
    metrics_json = Column(Text, nullable=True)  # JSON: accuracy, recall, precision, f1
    file_path = Column(String(512), nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False)
